//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x.Graph.Scenarios.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("x.Graph.Scenarios.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #edge data scenario
        ///---
        ///  0:   30.8
        ///  1:   31.4
        ///  2:   32.1
        ///  3:   33.0.
        /// </summary>
        internal static string edge_001_double {
            get {
                return ResourceManager.GetString("edge_001_double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #node data scenario
        ///---
        ///  0:   80.8
        ///  1:   40.4
        ///  2:    10.1
        ///  3:  10.0.
        /// </summary>
        internal static string node_001_double {
            get {
                return ResourceManager.GetString("node_001_double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///id: 1
        ///description: 
        ///node-count: 4 
        ///edge-count: 4
        ///
        ///nodes:
        ///    - id:    0
        ///      
        ///    - id:    1
        ///      
        ///    - id:    2
        ///      
        ///    - id:    3
        ///      
        ///edges:
        ///    - id:         0
        ///      source-id:  0
        ///      target-id:  1
        ///      
        ///    - id:         1
        ///      source-id:  0
        ///      target-id:  2
        ///      
        ///    - id:         2
        ///      source-id:  1
        ///      target-id:  3
        ///      
        ///    - id:         3
        ///      source-id:  2
        ///      target-id:  3	 
        ///.
        /// </summary>
        internal static string scenario_001 {
            get {
                return ResourceManager.GetString("scenario_001", resourceCulture);
            }
        }
    }
}
